# Generated by Django 5.0.2 on 2024-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.TextField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(default=None, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
